# NumPy Arrays


### python objects:

   > 1. high-level number objects: integers, floating point
   > 2. containers: lists (costless insertion and append), dictionaries (fast lookup)

### Numpy provides:

   > 1. extension package to Python for multi-dimensional arrays
   > 2. closer to hardware (efficiency)
   > 3. designed for scientific computation (convenience)
   > 4. Also known as array oriented computing



Arrays.PNG

In [2]:
import numpy as np # NumPy package imported as np
a = np.array([0, 1, 2, 3, 's']) # A list is converted into numpy array
print(a)
# print(type(a))
b = np.arange(10,21)
print(type(b)) # range of values from 0 to 9 are converted into arannge i.e. array range

['0' '1' '2' '3' 's']
<class 'numpy.ndarray'>


**Why it is useful:** Memory-efficient container that provides fast numerical operations.

In [ ]:
%timeit [i**2 for i in range(1000)]

1000 loops, best of 3: 260 µs per loop


In [ ]:
a = np.arange(1000)
%timeit a**2

The slowest run took 45.54 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.42 µs per loop


## 1. Creating NumPy Arrays

In [ ]:
# 1D array
a = np.array([1,2,3,4]) #created using list of 1D
print("Type of array is:",type(a))
print("array dimensions are",a.ndim)
print("Size of array is: ",a.shape)
print(a)
print("****************************************************")
#2D array
b = np.array([  [1,2,3,4],[7,8,9,0]  ]) #created using list of 2D
print(b)
print("Type of array is:",type(b))
print("array dimensions are",b.ndim)
print("Size of array is: ",b.shape)

print("****************************************************")
#3D array
c = np.array([  [   [0, 1], [2, 3]   ], [  [4, 5], [6, 7]  ]   ]) #created using list of 1D
print(c)
print("Type of array is:",type(c))
print("array dimensions are",c.ndim)
print("Size of array is: ",c.shape)

Type of array is: <class 'numpy.ndarray'>
array dimensions are 1
Size of array is:  (4,)
[1 2 3 4]
****************************************************
[[1 2 3 4]
 [7 8 9 0]]
Type of array is: <class 'numpy.ndarray'>
array dimensions are 2
Size of array is:  (2, 4)
****************************************************
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Type of array is: <class 'numpy.ndarray'>
array dimensions are 3
Size of array is:  (2, 2, 2)


### 1.1 Functions to create numpy arrays

In [ ]:
#using arrange function
# arange is an array-valued version of the built-in Python range function
a = np.arange(10) # 0.... n-1
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
b = np.arange(10,100,10) # arange is same like range() method
print(b)

[10 20 30 40 50 60 70 80 90]


In [3]:
c = np.linspace(10,20,11) # linspace stands for linear space which divides range 0 to 1 in 9 fragments
print(c)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [ ]:
#common arrays
# L = [1.0 for i in range(10)]
# a = np.array(L)
# print(a)
d = np.ones(10)
print(d)
print("********************************")
e = np.ones((3,2))
print(e)
print("********************************")
f = np.zeros((3,3,3))
print(f)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
********************************
[[1. 1.]
 [1. 1.]
 [1. 1.]]
********************************
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
g = np.eye(4,4) # creates a diagonal matrix with 1s at diagonal entries
print(g)
g = g.astype('int32')
print(g)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
h = np.diag([2.0,3.0,4.0]) # creates diagonal matrix with elements passed as list
print(h)

[[2. 0. 0.]
 [0. 3. 0.]
 [0. 0. 4.]]


In [ ]:
# To extract diagonal entries of an array
i = np.diag(h)
print(i)

[2. 3. 4.]


In [ ]:
# Create an array with random initialization

j = np.random.rand(4)
print(j*10)
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

[9.24998465 4.17456572 0.81092976 7.29878322]


In [ ]:
k = np.random.randn(10)
print(k) #Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

[-0.13430485  2.32366784  2.55569862 -0.77726662  0.03923456  1.76839383
  0.1151954   0.6230519  -0.52423696 -0.21486054]


In [ ]:
import numpy as np
# To create an array inintialized with givrn number
a = np.full((2,3),9.0)
a

array([[9., 9., 9.],
       [9., 9., 9.]])

## 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a trailing dot (e.g. 2. vs 2). This is due to a difference in the data-type used:


In [ ]:
arr = np.arange(10) # this will create an array of integer elements
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [5]:
# To create an array of ffloat we have to mention explicitly
arrF = np.arange(10, dtype="int64")
print(arrF)
print(type(arrF))
print(arrF.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64


In [6]:
zarr = np.zeros((10,10),dtype="int64")
print(type(zarr))
print(zarr.dtype)

<class 'numpy.ndarray'>
int64


In [ ]:
xarr = np.array([2+8j, 3+9j])
print(type(xarr))
print(xarr.dtype)

<class 'numpy.ndarray'>
complex128


In [ ]:
barr = np.array([True, False])
print(type(barr))
print(barr.dtype)

<class 'numpy.ndarray'>
bool


In [ ]:
sarr = np.array(["Python","java","MachineLearning"])
print(sarr)
print(type(sarr))
print(sarr.dtype)

['Python' 'java' 'MachineLearning']
<class 'numpy.ndarray'>
<U15


#### Each built-in data type has a character code that uniquely identifies it.

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)


## 3. Indexing and Slicing

### 3.1 Indexing

The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):


In [7]:
a = np.arange(10)
print(a)
print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

[0 1 2 3 4 5 6 7 8 9]
5


In [ ]:
b = np.diag([3,4,5])
print(b)

print(b[0][0])


[[3 0 0]
 [0 4 0]
 [0 0 5]]
3


In [9]:
c = np.array([  [   [0, 1], [2, 3]   ], [  [4, 5], [6, 7]  ]   ])
print(c)
print(c[0][1][1])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3


### 3.2 Slicing

In [11]:
array = np.arange(10)
print(array)
print(array[0:10:2])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [13]:
array[5:7] = 90
print(array)

[ 0  1  2  3  4 90 90  7  8  9]


In [14]:
b = np.arange(5)
array[0:5] = b[::-1]
print(array)

[ 4  3  2  1  0 90 90  7  8  9]


In [30]:
b = np.diag([3,4,5])
print(b)
print("*"*10)
b[2][1:] = 99
print(b)

[[3 0 0]
 [0 4 0]
 [0 0 5]]
**********
[[ 3  0  0]
 [ 0  4  0]
 [ 0 99 99]]


### 4. Copies and Views

1. A slicing operation creates a view on the original array, which is just a way of accessing array data. 
2. Thus the original array is not copied in memory. 
3. You can use np.may_share_memory ( ) to check if two arrays share the same memory block.
4. When modifying the view, the original array is modified as well:

In [33]:
arrA = np.arange(10)

arrB = arrA[::2] # arrB also points to arrA by sharing memory
print("arrA: ",arrA)
print("arrB: ",arrB)

# print("Address of arrA: ",id(arrA))
# print("Address of arrB: ",id(arrB))
# print("\n arrA & arrB shares Memory? ", np.shares_memory(arrA,arrB))
arrA[4] = 999

print("\n arrA: ",arrA) # Both arrA and arrB shares same memory as data is allocated using slicing
print(" arrB: ",arrB) 



arrA:  [0 1 2 3 4 5 6 7 8 9]
arrB:  [0 2 4 6 8]

 arrA:  [  0   1   2   3 999   5   6   7   8   9]
 arrB:  [  0   2 999   6   8]


In [ ]:
# To force a copy  we have to use copy() method from NumPy
arrA = np.arange(10)

arrB = arrA[::2].copy()
print("arrA: ",arrA)
print("arrB: ",arrB)

print("Address of arrA: ",id(arrA))
print("Address of arrB: ",id(arrB))
print("\n arrA & arrB shares Memory? ", np.shares_memory(arrA,arrB))
arrB[4] = 999

print("\n arrA: ",arrA) # Both arrA and arrB do not shares same memory as data is allocated using copy()
print(" arrB: ",arrB) 

arrA:  [0 1 2 3 4 5 6 7 8 9]
arrB:  [0 2 4 6 8]
Address of arrA:  139899563676896
Address of arrB:  139899563676416

 arrA & arrB shares Memory?  False

 arrA:  [0 1 2 3 4 5 6 7 8 9]
 arrB:  [  0   2   4   6 999]


### 5. Fancy Indexing

In [37]:
arr = np.arange(5)
print(arr)
mask = (arr%2 == 0)
print(mask)

arrB = arr[mask] # mask statement is "mapped" to arr and whenever the statement is true then only data is
                 # allocated to arrB

print("arr: ",arr)
print("arrB: ",arrB)

[0 1 2 3 4]
[ True False  True False  True]
arr:  [0 1 2 3 4]
arrB:  [0 2 4]


In [ ]:
arr[mask] = -1 # all places in arr where even numbers were there replaced with -1
print(arr)

[-1  1 -1  3 -1  5 -1  7 -1  9]


Indexing with an array of integers

In [ ]:
a = np.arange(0, 100, 10)

print(a)
#Indexing can be done with an array of integers, where the same index is repeated several time:

print(a[[2, 3, 2, 4, 2]])

[ 0 10 20 30 40 50 60 70 80 90]
[20 30 20 40 20]


In [ ]:
# New values can be assigned 

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])